
// File generated by Go version U-2022.12#33f3808fcb#221128, Wed Feb 21 17:37:23 2024
// Copyright 2014-2022 Synopsys, Inc. All rights reserved.
// go -I../lib -F -D__tct_patch__=0 -Verilog -otrv32p3_cnn_vlog-c1 -cgo_options-c1.cfg -Itrv32p3_cnn_vlog-c1/tmp_pdg -updg -updg_controller trv32p3_cnn



`timescale 1ns/1ps

// module mux_ocd_swbreak : mux_ocd_swbreak
module mux_ocd_swbreak
  ( input      ohe_selector_EX,
    output reg ocd_swbreak_out // t1u
  );


  // synopsys dc_tcl_script_begin
  // set_ungroup [current_design]
  // synopsys dc_tcl_script_end
  always @ (*)

  begin : p_mux_ocd_swbreak

    ocd_swbreak_out = 1'h0; // hw_init

    if (ohe_selector_EX) // (ocd_swbreak_copy0___CTt1u_cstV1_EX)
    begin
      // [ocd.n:111]
      ocd_swbreak_out = 1'h1;
    end

  end

endmodule
