
// File generated by Go version U-2022.12#33f3808fcb#221128, Wed Feb 21 13:01:43 2024
// Copyright 2014-2022 Synopsys, Inc. All rights reserved.
// go -I../lib -F -D__tct_patch__=0 -Verilog -otrv32p3_cnn_vlog-c1 -cgo_options-c1.cfg -Itrv32p3_cnn_vlog-c1/tmp_pdg -updg -updg_controller trv32p3_cnn



`timescale 1ns/1ps

// module mux_aluB : mux_aluB
module mux_aluB
  ( input              [1:0] bin_selector_EX,
    input              [4:0] __CTt5u_cstP20_EX_in, // t5u
    input      signed [11:0] __CTt12s_cstP20_EX_in, // t12s
    input      signed [19:0] __CTt20s_rp12_cstP12_EX_in, // t20s_rp12
    input      signed [31:0] x_r2_in, // w32
    output reg signed [31:0] aluB_out // w32
  );


  // synopsys dc_tcl_script_begin
  // set_ungroup [current_design]
  // synopsys dc_tcl_script_end
  always @ (*)

  begin : p_mux_aluB

    aluB_out = 32'sh0;

    case (bin_selector_EX)
      2'b00 : // (aluB_copy0___CTt12s_cstP20_EX)
      begin
        // [alu.n:132]
        aluB_out = $signed({{20{__CTt12s_cstP20_EX_in[11]}}, __CTt12s_cstP20_EX_in});
      end
      2'b01 : // (aluB_copy0___CTt20s_rp12_cstP12_EX)
      begin
        // [alu.n:211]
        aluB_out = $signed({__CTt20s_rp12_cstP12_EX_in, 12'b000000000000});
      end
      2'b10 : // (aluB_copy0___CTt5u_cstP20_EX)
      begin
        // [alu.n:168]
        aluB_out = $signed({{27{1'b0}}, __CTt5u_cstP20_EX_in});
      end
      default : // (aluB_copy0_x_r2_EX)
      begin
        // [alu.n:70](regX.n:82)
        aluB_out = x_r2_in;
      end
    endcase

  end

endmodule
