
-- File generated by Go version U-2022.12#33f3808fcb#221128, Wed Feb 21 17:37:19 2024
-- Copyright 2014-2022 Synopsys, Inc. All rights reserved.
-- go -I../lib -F -DIS_VHDL -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -VHDL -otrv32p3_cnn_vhdl -cgo_options.cfg -Itrv32p3_cnn_vhdl/tmp_pdg -updg -updg_controller trv32p3_cnn



architecture rtl of mem_PMb is

begin

  p_mem_PMb : process(ocd_ld_PMbEX_r_in,
                      ocd_st_PMbEX_r_in,
                      pm_ld_pdg_en_in,
                      pm_addr_dp_in,
                      pm_rd_in,
                      pm_wr_dp_in)

  begin
    pm_addr_out <= (others => '0');
    pm_ld_out <= '0';
    -- pm_rd_dp_out <= (others => '0');
    pm_st_out <= '0';
    pm_wr_out <= (others => '0');

    -- (cp_extin_pm_rd_ld_PM_pm_addr___ocd_ld_PMbEX_r_EX_alw, cp_extad_PM_st_pm_wr_pm_addr___ocd_st_PMbEX_r_EX_alw, cp_extad_pm_rd_ld_PM_pm_addr___ocd_ld_PMbEX_r_EX_alw, cp_extout_PM_st_pm_wr_pm_addr___ocd_st_PMbEX_r_EX_alw, cp_extin_pm_rd_rd_PM_pm_addr_pm_ld_pdg_en, mem_enab_PM_st_pm_wr_pm_addr___ocd_st_PMbEX_r_EX_alw, mem_enab_pm_rd_ld_PM_pm_addr___ocd_ld_PMbEX_r_EX_alw, mem_enab_pm_rd_rd_PM_pm_addr_pm_ld_pdg_en, cp_extad_pm_rd_rd_PM_pm_addr_pm_ld_pdg_en)
    -- [ocd.n:89]
    pm_rd_dp_out <= pm_rd_in;
    if ocd_st_PMbEX_r_in then
      -- [ocd.n:95]
      pm_addr_out <= pm_addr_dp_in;
    end if;
    if ocd_ld_PMbEX_r_in then
      -- [ocd.n:89]
      pm_addr_out <= pm_addr_dp_in;
    end if;
    if ocd_st_PMbEX_r_in then
      -- [ocd.n:95]
      pm_wr_out <= pm_wr_dp_in;
    end if;
    if ocd_st_PMbEX_r_in then
      -- [ocd.n:95]
      pm_st_out <= '1';
    end if;
    if ocd_ld_PMbEX_r_in then
      -- [ocd.n:89]
      pm_ld_out <= '1';
    end if;
    if pm_ld_pdg_en_in = '1' then
      pm_ld_out <= '1';
      pm_addr_out <= pm_addr_dp_in;
    end if;

  end process p_mem_PMb;

end rtl;
