
// File generated by Go version U-2022.12#33f3808fcb#221128, Wed Feb  7 12:11:44 2024
// Copyright 2014-2022 Synopsys, Inc. All rights reserved.
// go -I../lib -F -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -Verilog -otrv32p3_cnn_vlog -cgo_options.cfg -Itrv32p3_cnn_vlog/tmp_pdg -updg -updg_controller trv32p3_cnn



`timescale 1ns/1ps

// module mux_cnn_w1 : mux_cnn_w1
module mux_cnn_w1
  ( input                    ohe_selector_EX,
    input      signed [31:0] cnn_R_in, // w32
    input      signed [31:0] cnn_w11_in, // w32
    output reg signed [31:0] cnn_w1_out // w32
  );


  always @ (*)

  begin : p_mux_cnn_w1

    // cnn_w1_out = 32'sh0;

    // (cnn_w1_copy0_cnn_R_EX)
    // [cnn.n:38]
    cnn_w1_out = cnn_R_in;

    if (ohe_selector_EX) // (cnn_w1_copy_cnn_w11_EX)
    begin
      // [cnn.n:56]
      cnn_w1_out = cnn_w11_in;
    end

  end

endmodule
