
// File generated by Go version U-2022.12#33f3808fcb#221128, Wed Apr 10 15:55:47 2024
// Copyright 2014-2022 Synopsys, Inc. All rights reserved.
// go -I../lib -F -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -Verilog -otrv32p3_cnn_vlog -cgo_options.cfg -Itrv32p3_cnn_vlog/tmp_pdg -updg -updg_controller trv32p3_cnn



`timescale 1ns/1ps

// module mux_cnn_r1 : mux_cnn_r1
module mux_cnn_r1
  ( input                    ohe_selector_EX,
    input      signed [31:0] x_r1_in, // w32
    input      signed [31:0] x_r4_in, // w32
    output reg signed [31:0] cnn_r1_out // w32
  );


  always @ (*)

  begin : p_mux_cnn_r1

    // cnn_r1_out = 32'sh0;

    // (cnn_r1_copy0_x_r1_EX)
    // [cnn.n:53](regX.n:77)
    cnn_r1_out = x_r1_in;

    if (ohe_selector_EX) // (cnn_r1_copy0_x_r4_EX)
    begin
      // [cnn.n:77]
      cnn_r1_out = x_r4_in;
    end

  end

endmodule
