
// File generated by Go version U-2022.12#33f3808fcb#221128, Sat Mar 16 14:40:42 2024
// Copyright 2014-2022 Synopsys, Inc. All rights reserved.
// go -I../lib -F -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -Verilog -otrv32p3_cnn_vlog -cgo_options.cfg -Itrv32p3_cnn_vlog/tmp_pdg -updg -updg_controller trv32p3_cnn



`timescale 1ns/1ps

// module mux_aguA : mux_aguA
module mux_aguA
  ( input                    ohe_selector_ID,
    input      signed [31:0] x_r3_in, // w32
    input      signed [31:0] x_r4_in, // w32
    output reg signed [31:0] aguA_out // w32
  );


  always @ (*)

  begin : p_mux_aguA

    // aguA_out = 32'sh0;

    // (aguA_copy0_x_r3_ID)
    // [ldst.n:54][ldst.n:91](regX.n:91)
    aguA_out = x_r3_in;

    if (ohe_selector_ID) // (aguA_copy0_x_r4_ID)
    begin
      // [cnn.n:96]
      aguA_out = x_r4_in;
    end

  end

endmodule
