
-- File generated by Go version U-2022.12#33f3808fcb#221128, Wed Feb 21 17:37:19 2024
-- Copyright 2014-2022 Synopsys, Inc. All rights reserved.
-- go -I../lib -F -DIS_VHDL -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -VHDL -otrv32p3_cnn_vhdl -cgo_options.cfg -Itrv32p3_cnn_vhdl/tmp_pdg -updg -updg_controller trv32p3_cnn



architecture rtl of reg_ocd_addr is

  signal reg_val : t_addr;
  -- synopsys translate_off
  signal reg_write_log     : std_logic := '0';
  -- synopsys translate_on

begin

  -- synopsys translate_off
  p_reg_ocd_addr_log : process(clock)

    procedure log_reg_ocd_addr(reg_val : in t_addr) is
      variable lline : line;
      variable val_ok : boolean := true;
    begin
      write(lline, string'("ocd_addr"));
      write(lline, string'(" = "));
      for j in reg_val'range loop
        if reg_val(j) /= '0' and reg_val(j) /= '1' then
          val_ok := false;
          exit;
        end if;
      end loop;
      if val_ok then
        hwrite(lline, std_logic_vector(reg_val));
      else
        write(lline, string'("X"));
      end if;
      logfile_write(lline);
    end log_reg_ocd_addr;

  begin

    if clock'event and clock = '0' then
      if reg_log_gen then
        if reg_write_log = '1' then
          log_reg_ocd_addr(reg_val);
        end if;
      end if;
    end if;
  end process p_reg_ocd_addr_log;
  -- synopsys translate_on

  p_read_reg_ocd_addr : process(reg_val)
  begin
    -- ocd_addr_pdcr_out <= (others => '0');
    -- ocd_addr_r_out <= (others => '0');

    -- (ocd_addr_pdcr_rd_ocd_addr, ocd_addr_r_rd_ocd_addr_alw)
    ocd_addr_pdcr_out <= reg_val;
    -- [ocd.n:63]
    ocd_addr_r_out <= reg_val;

  end process p_read_reg_ocd_addr;

  p_write_reg_ocd_addr : process(clock, reset)
  begin
    if reset /= '0' then
      -- synopsys translate_off
      reg_write_log <= '0';
      -- synopsys translate_on
      reg_val <= to_unsigned(0, t_addr'length);
    elsif clock'event and clock = '1' then
      -- synopsys translate_off
      reg_write_log <= '0';
      -- synopsys translate_on

      -- (ocd_addr_wr_ocd_addr_w___ocd_ld_DMbEX_r_EX_alw, ocd_addr_wr_ocd_addr_w___ocd_ld_PMbEX_r_EX_alw, ocd_addr_wr_ocd_addr_w___ocd_st_DMbEX_r_EX_alw, ocd_addr_wr_ocd_addr_w___ocd_st_PMbEX_r_EX_alw, ocd_addr_wr_ocd_addr_pdcw)
      if ocd_ld_DMbEX_r_in then
        -- [ocd.n:71]
        -- synopsys translate_off
        reg_write_log <= '1';
        -- synopsys translate_on
        reg_val <= ocd_addr_w_in;
      end if;
      if ocd_ld_PMbEX_r_in then
        -- [ocd.n:87]
        -- synopsys translate_off
        reg_write_log <= '1';
        -- synopsys translate_on
        reg_val <= ocd_addr_w_in;
      end if;
      if ocd_st_DMbEX_r_in then
        -- [ocd.n:78]
        -- synopsys translate_off
        reg_write_log <= '1';
        -- synopsys translate_on
        reg_val <= ocd_addr_w_in;
      end if;
      if ocd_st_PMbEX_r_in then
        -- [ocd.n:94]
        -- synopsys translate_off
        reg_write_log <= '1';
        -- synopsys translate_on
        reg_val <= ocd_addr_w_in;
      end if;
      if en_ocd_addr_pdcw_in = '1' then
        -- synopsys translate_off
        reg_write_log <= '1';
        -- synopsys translate_on
        reg_val <= ocd_addr_pdcw_in;
      end if;

    end if;
  end process p_write_reg_ocd_addr;

end rtl;
