
-- File generated by Go version U-2022.12#33f3808fcb#221128, Wed Feb 21 17:37:19 2024
-- Copyright 2014-2022 Synopsys, Inc. All rights reserved.
-- go -I../lib -F -DIS_VHDL -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -VHDL -otrv32p3_cnn_vhdl -cgo_options.cfg -Itrv32p3_cnn_vhdl/tmp_pdg -updg -updg_controller trv32p3_cnn



library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library trv32p3_cnn_lib;
use trv32p3_cnn_lib.data_types.all;
-- synopsys translate_off
use std.textio.all;
use ieee.std_logic_textio.all;
-- synopsys translate_on

-- entity reg_PC_EX : reg_PC_EX
entity reg_PC_EX is
  -- synopsys translate_off
  generic (
    reg_log_gen : boolean := true);
  -- synopsys translate_on

  port (
    clock : in std_logic;
    ohe_selector_ID : in std_logic;
    PC_EX_w_in : in t_addr;
    hzd_stall_in : in std_logic;
    kill_ID_in : in std_logic;
    PC_EX_r_out : out t_addr);
end reg_PC_EX;
