
-- File generated by Go version U-2022.12#33f3808fcb#221128, Wed Feb 21 13:01:39 2024
-- Copyright 2014-2022 Synopsys, Inc. All rights reserved.
-- go -I../lib -F -DIS_VHDL -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -VHDL -otrv32p3_cnn_vhdl -cgo_options.cfg -Itrv32p3_cnn_vhdl/tmp_pdg -updg -updg_controller trv32p3_cnn



library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library trv32p3_cnn_lib;
use trv32p3_cnn_lib.data_types.all;
-- synopsys translate_off
use std.textio.all;
use ieee.std_logic_textio.all;
-- synopsys translate_on

-- entity reg_X : reg_X
entity reg_X is
  -- synopsys translate_off
  generic (
    reg_log_gen : boolean := true);
  -- synopsys translate_on

  port (
    reset : in std_logic;
    clock : in std_logic;
    bin_selector_EX : in std_logic_vector(1 downto 0);
    X_x_w1_div_main_pdg_en_in : in t_uint1_t;
    X_x_r1_raddr_in : in t_t5u;
    X_x_r2_raddr_in : in t_t5u;
    X_x_r3_raddr_in : in t_t5u;
    X_x_w1_wad_in : in t_t5u;
    X_x_w2_waddr_in : in t_t5u;
    x_w1_in : in t_w32;
    x_w2_in : in t_w32;
    x_r1_out : out t_w32;
    x_r2_out : out t_w32;
    x_r3_out : out t_w32);
end reg_X;
