
# File generated by Go version U-2022.12#33f3808fcb#221128, Wed Feb 21 13:01:41 2024
# Copyright 2014-2022 Synopsys, Inc. All rights reserved.
# go -I../lib -F -D__tct_patch__=0 -Verilog -otrv32p3_cnn_vlog-isacov -cgo_options-isacov.cfg -Itrv32p3_cnn_vlog-isacov/tmp_pdg -updg -updg_controller trv32p3_cnn



dump -add / -depth 0
