
// File generated by pdg version U-2022.12#33f3808fcb#221128
// Copyright 2014-2022 Synopsys, Inc. All rights reserved.
// pdg -P -Iisg +wisg -D__tct_patch__=0 -D__checkers__ trv32p3_cnn

#include <cstdio>
#include <iostream>
#include <iomanip>
#include <map>
#include <set>
#include <string>
#include <sstream>
#include <fstream>
#include <cassert>

#include "trv32p3_cnn_iss_types.h"

#ifdef PDG_INLINE_PRIMITIVES
#include "trv32p3_cnn_inline_primitives.h"
#endif

#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wparentheses"
#endif

using namespace trv32p3_cnn_primitive;

std::string current_line;

#if (defined(_MSC_VER) && _MSC_VER < 1300)

std::ostream& operator<<(std::ostream& os, long long n)
{
    char buf[128];
    if (os.flags() & std::ios_base::hex) {
        sprintf(buf, "%I64x", n);
    }
    else if (os.flags() & std::ios_base::oct) {
        sprintf(buf, "%I64o", n);
    }
    else {
        sprintf(buf, "%I64d", n);
    }
    os << buf;
    return os;
}

std::ostream& operator<<(std::ostream& os, unsigned long long n)
{
    char buf[128];
    if (os.flags() & std::ios_base::hex) {
        sprintf(buf, "%I64x", n);
    }
    else if (os.flags() & std::ios_base::oct) {
        sprintf(buf, "%I64o", n);
    }
    else {
        sprintf(buf, "%I64d", n);
    }
    os << buf;
    return os;
}
std::istream& operator>>(std::istream& is, long long& n)
{
    n = 0;

    int ndg = 0;

    char c;
    is >> c;
    if (!is)
        return is;
    int neg = 0;
    if (c == '-') {
        neg = 1;
        is.get(c);
        if (!is)
            return is;
    }
    if (is.flags() & std::ios_base::hex) {
        int done = 0;
        while(is && !done) {
            switch(c) {
                case '0': n = n*16     ; ndg++; break;
                case '1': n = n*16 +  1; ndg++; break;
                case '2': n = n*16 +  2; ndg++; break;
                case '3': n = n*16 +  3; ndg++; break;
                case '4': n = n*16 +  4; ndg++; break;
                case '5': n = n*16 +  5; ndg++; break;
                case '6': n = n*16 +  6; ndg++; break;
                case '7': n = n*16 +  7; ndg++; break;
                case '8': n = n*16 +  8; ndg++; break;
                case '9': n = n*16 +  9; ndg++; break;
                case 'a':
                case 'A': n = n*16 + 10; ndg++; break;
                case 'b':
                case 'B': n = n*16 + 11; ndg++; break;
                case 'c':
                case 'C': n = n*16 + 12; ndg++; break;
                case 'd':
                case 'D': n = n*16 + 13; ndg++; break;
                case 'e':
                case 'E': n = n*16 + 14; ndg++; break;
                case 'f':
                case 'F': n = n*16 + 15; ndg++; break;
                case 'x':
                case 'X':
                    if (ndg == 1 && n == 0)
                        ndg = 0;
                    else
                        done = 1;
                    break;
                default:
                    done = 1;
            }
            if (done)
                is.putback(c);
            else
                is.get(c);
        }
        if (ndg > 0)
            is.clear(std::ios_base::goodbit);
        else
            is.clear(std::ios_base::badbit|is.rdstate());
        if (neg)
            n = -n;
    }
    else if (is.flags() & std::ios_base::oct) {
        int done = 0;
        while(is && !done) {
            switch(c) {
                case '0': n = n*8    ; ndg++; break;
                case '1': n = n*8 + 1; ndg++; break;
                case '2': n = n*8 + 2; ndg++; break;
                case '3': n = n*8 + 3; ndg++; break;
                case '4': n = n*8 + 4; ndg++; break;
                case '5': n = n*8 + 5; ndg++; break;
                case '6': n = n*8 + 6; ndg++; break;
                case '7': n = n*8 + 7; ndg++; break;
                default:
                    done = 1;
            }
            if (done)
                is.putback(c);
            else
                is.get(c);
        }
        if (ndg > 0)
            is.clear(std::ios_base::goodbit);
        else
            is.clear(std::ios_base::badbit|is.rdstate());
        if (neg)
            n = -n;
    }
    else { // dec
        int done = 0;
        while(is && !done) {
            switch(c) {
                case '0': n = n*10    ; ndg++; break;
                case '1': n = n*10 + 1; ndg++; break;
                case '2': n = n*10 + 2; ndg++; break;
                case '3': n = n*10 + 3; ndg++; break;
                case '4': n = n*10 + 4; ndg++; break;
                case '5': n = n*10 + 5; ndg++; break;
                case '6': n = n*10 + 6; ndg++; break;
                case '7': n = n*10 + 7; ndg++; break;
                case '8': n = n*10 + 8; ndg++; break;
                case '9': n = n*10 + 9; ndg++; break;
                default :
                    done = 1;
            }
            if (done)
                is.putback(c);
            else
                is.get(c);
        }
        if (ndg > 0)
            is.clear(std::ios_base::goodbit);
        else
            is.clear(std::ios_base::badbit|is.rdstate());
        if (neg)
            n = -n;
    }
    return is;
}

std::istream& operator>>(std::istream& is, unsigned long long& n)
{
    long long t;
    is >> t;
    if (is)
        n = t;
    return is;
}
#endif

typedef bool boolean;

int pdg_error_count = 0;
std::ostream* error_stream;

template <typename T>
void failure(const T& t1, const T& t2) {
    ++pdg_error_count;
    *error_stream << current_line << " ; expected " << t1 << ", found " << t2 << std::endl;
    std::cerr << current_line << " ; expected " << t1 << ", found " << t2 << '\n';
}

template <typename T>
void read_from_stream(std::istream& is, T& result) {
    unsigned u;
    is >> u;
    result = u;
}
template <typename T>
void read_from_stream_ll(std::istream& is, T& result) {
    unsigned long long ull;
    is >> ull;
    result = ull;
}
static bool between(char l, char x, char h) {
    return l <= x && x <= h;
}

static unsigned digit2hex(char c) {
    if (between('0', c, '9')) {
        return c - '0';
    } else if (between('a', c, 'f')) {
        return c - 'a' + 10;
    } else if (between('A', c, 'F')) {
        return c - 'A' + 10;
    }
    return 0;
}

void read_from_stream_lla(std::istream& is, unsigned long long* result, const unsigned n) {
    const int octo_count = CHESS_LLAS(n);
    const int hex_digits = (n + 3) / 4;
    for (int i = 0; i < octo_count; ++i) {
        unsigned long long ull = 0;
        for (int j = 0; j < ((i == 0 && hex_digits % 16) ? hex_digits % 16 : 16); ++j) {
            ull <<= 4;
            char c;
            is >> c;
            ull += digit2hex(c);
        }
        result[octo_count - i - 1] = ull;
    }
}

void read_from_stream_lla(std::istream& is, long long* result, const unsigned n) {
    const int octo_count = CHESS_LLAS(n);
    const int hex_digits = (n + 3) / 4;
    for (int i = 0; i < octo_count; ++i) {
        unsigned long long ull = 0;
        for (int j = 0; j < ((i == 0 && hex_digits % 16) ? hex_digits % 16 : 16); ++j) {
            ull <<= 4;
            char c;
            is >> c;
            ull += digit2hex(c);
        }
        result[octo_count - i - 1] = ull;
    }
    if (n % 64) result[octo_count - 1] = CHESS_EXTENDLL(result[octo_count - 1], n % 64);
}

unsigned long long buf_ull[1024];
unsigned long long buf_ull2[1024];
long long buf_ll[1024];
long long buf_ll2[1024];

bool operator!=(trv32p3_cnn_primitive::addr x1, trv32p3_cnn_primitive::addr x2) {
    return toVBit(x1) != toVBit(x2);
}

bool operator!=(trv32p3_cnn_primitive::iword x1, trv32p3_cnn_primitive::iword x2) {
    return toVBit(x1) != toVBit(x2);
}

bool operator!=(trv32p3_cnn_primitive::t12s x1, trv32p3_cnn_primitive::t12s x2) {
    return toVBit(x1) != toVBit(x2);
}

bool operator!=(trv32p3_cnn_primitive::t13s_s2 x1, trv32p3_cnn_primitive::t13s_s2 x2) {
    return toVBit(x1) != toVBit(x2);
}

bool operator!=(trv32p3_cnn_primitive::t1u x1, trv32p3_cnn_primitive::t1u x2) {
    return toVBit(x1) != toVBit(x2);
}

bool operator!=(trv32p3_cnn_primitive::t20s_rp12 x1, trv32p3_cnn_primitive::t20s_rp12 x2) {
    return toVBit(x1) != toVBit(x2);
}

bool operator!=(trv32p3_cnn_primitive::t21s_s2 x1, trv32p3_cnn_primitive::t21s_s2 x2) {
    return toVBit(x1) != toVBit(x2);
}

bool operator!=(trv32p3_cnn_primitive::t2u x1, trv32p3_cnn_primitive::t2u x2) {
    return toVBit(x1) != toVBit(x2);
}

bool operator!=(trv32p3_cnn_primitive::t31s_rp1 x1, trv32p3_cnn_primitive::t31s_rp1 x2) {
    return toVBit(x1) != toVBit(x2);
}

bool operator!=(trv32p3_cnn_primitive::t5u x1, trv32p3_cnn_primitive::t5u x2) {
    return toVBit(x1) != toVBit(x2);
}

bool operator!=(trv32p3_cnn_primitive::t5unz x1, trv32p3_cnn_primitive::t5unz x2) {
    return toVBit(x1) != toVBit(x2);
}

bool operator!=(trv32p3_cnn_primitive::u08 x1, trv32p3_cnn_primitive::u08 x2) {
    return toVBit(x1) != toVBit(x2);
}

bool operator!=(trv32p3_cnn_primitive::v22w32 x1, trv32p3_cnn_primitive::v22w32 x2) {
    return toVBit(x1) != toVBit(x2);
}

bool operator!=(trv32p3_cnn_primitive::w08 x1, trv32p3_cnn_primitive::w08 x2) {
    return toVBit(x1) != toVBit(x2);
}

bool operator!=(trv32p3_cnn_primitive::w16 x1, trv32p3_cnn_primitive::w16 x2) {
    return toVBit(x1) != toVBit(x2);
}

bool operator!=(trv32p3_cnn_primitive::w32 x1, trv32p3_cnn_primitive::w32 x2) {
    return toVBit(x1) != toVBit(x2);
}

void test_w32_add_w32_w32(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w32 t0;
    trv32p3_cnn_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = add(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_sub_w32_w32(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w32 t0;
    trv32p3_cnn_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = sub(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_slt_w32_w32(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w32 t0;
    trv32p3_cnn_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = slt(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_sltu_w32_w32(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w32 t0;
    trv32p3_cnn_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = sltu(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_seq0_w32(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w32 t0;
    read_from_stream(is, t0);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = seq0(t0);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_sne0_w32(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w32 t0;
    read_from_stream(is, t0);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = sne0(t0);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_mul_w32_w32(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w32 t0;
    trv32p3_cnn_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = mul(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_mulh_w32_w32(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w32 t0;
    trv32p3_cnn_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = mulh(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_mulhsu_w32_w32(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w32 t0;
    trv32p3_cnn_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = mulhsu(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_mulhu_w32_w32(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w32 t0;
    trv32p3_cnn_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = mulhu(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_band_w32_w32(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w32 t0;
    trv32p3_cnn_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = band(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_bor_w32_w32(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w32 t0;
    trv32p3_cnn_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = bor(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_bxor_w32_w32(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w32 t0;
    trv32p3_cnn_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = bxor(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_bool_eq_w32_w32(std::istream& is) {
    bool result_expected;
    trv32p3_cnn_primitive::w32 t0;
    trv32p3_cnn_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    bool result = eq(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_bool_ne_w32_w32(std::istream& is) {
    bool result_expected;
    trv32p3_cnn_primitive::w32 t0;
    trv32p3_cnn_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    bool result = ne(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_bool_lt_w32_w32(std::istream& is) {
    bool result_expected;
    trv32p3_cnn_primitive::w32 t0;
    trv32p3_cnn_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    bool result = lt(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_bool_ge_w32_w32(std::istream& is) {
    bool result_expected;
    trv32p3_cnn_primitive::w32 t0;
    trv32p3_cnn_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    bool result = ge(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_bool_ltu_w32_w32(std::istream& is) {
    bool result_expected;
    trv32p3_cnn_primitive::w32 t0;
    trv32p3_cnn_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    bool result = ltu(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_bool_geu_w32_w32(std::istream& is) {
    bool result_expected;
    trv32p3_cnn_primitive::w32 t0;
    trv32p3_cnn_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    bool result = geu(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_sra_w32_w32(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w32 t0;
    trv32p3_cnn_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = sra(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_sll_w32_w32(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w32 t0;
    trv32p3_cnn_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = sll(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_srl_w32_w32(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w32 t0;
    trv32p3_cnn_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = srl(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_sext_w08(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w08 t0;
    read_from_stream(is, t0);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = sext(t0);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_zext_w08(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w08 t0;
    read_from_stream(is, t0);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = zext(t0);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_sext_w16(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w16 t0;
    read_from_stream(is, t0);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = sext(t0);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_zext_w16(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w16 t0;
    read_from_stream(is, t0);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = zext(t0);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_void_nop(std::istream& is) {
    nop();
}

void test_void_mul_hw_w32_w32_t2u_w32_w32(std::istream& is) {
    trv32p3_cnn_primitive::w32 t0;
    trv32p3_cnn_primitive::w32 t1;
    trv32p3_cnn_primitive::t2u t2;
    trv32p3_cnn_primitive::w32 t3;
    trv32p3_cnn_primitive::w32 t3_expected;
    trv32p3_cnn_primitive::w32 t4;
    trv32p3_cnn_primitive::w32 t4_expected;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, t2);
    read_from_stream(is, t3_expected);
    read_from_stream(is, t4_expected);
    mul_hw(t0, t1, t2, t3, t4);
    if (t3 != t3_expected) { failure(t3_expected, t3); return; }
    if (t4 != t4_expected) { failure(t4_expected, t4); return; }
}

void test_w32_divs_w32_w32(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w32 t0;
    trv32p3_cnn_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = divs(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_rems_w32_w32(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w32 t0;
    trv32p3_cnn_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = rems(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_divu_w32_w32(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w32 t0;
    trv32p3_cnn_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = divu(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_remu_w32_w32(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w32 t0;
    trv32p3_cnn_primitive::w32 t1;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = remu(t0, t1);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_mac_w32_w32_w32(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w32 t0;
    trv32p3_cnn_primitive::w32 t1;
    trv32p3_cnn_primitive::w32 t2;
    read_from_stream(is, t0);
    read_from_stream(is, t1);
    read_from_stream(is, t2);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = mac(t0, t1, t2);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_exp_w32(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w32 t0;
    read_from_stream(is, t0);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = exp(t0);
    if (result != result_expected) { failure(result_expected, result); return; }
}

void test_w32_prelu_w32(std::istream& is) {
    trv32p3_cnn_primitive::w32 result_expected;
    trv32p3_cnn_primitive::w32 t0;
    read_from_stream(is, t0);
    read_from_stream(is, result_expected);
    trv32p3_cnn_primitive::w32 result = prelu(t0);
    if (result != result_expected) { failure(result_expected, result); return; }
}
typedef std::map<std::string, void(*)(std::istream&)> TestDrivers;
void register_drivers0(TestDrivers& test_drivers) {
    test_drivers["w32_add_w32_w32"] = test_w32_add_w32_w32;
    test_drivers["w32_sub_w32_w32"] = test_w32_sub_w32_w32;
    test_drivers["w32_slt_w32_w32"] = test_w32_slt_w32_w32;
    test_drivers["w32_sltu_w32_w32"] = test_w32_sltu_w32_w32;
    test_drivers["w32_seq0_w32"] = test_w32_seq0_w32;
    test_drivers["w32_sne0_w32"] = test_w32_sne0_w32;
    test_drivers["w32_mul_w32_w32"] = test_w32_mul_w32_w32;
    test_drivers["w32_mulh_w32_w32"] = test_w32_mulh_w32_w32;
    test_drivers["w32_mulhsu_w32_w32"] = test_w32_mulhsu_w32_w32;
    test_drivers["w32_mulhu_w32_w32"] = test_w32_mulhu_w32_w32;
    test_drivers["w32_band_w32_w32"] = test_w32_band_w32_w32;
    test_drivers["w32_bor_w32_w32"] = test_w32_bor_w32_w32;
    test_drivers["w32_bxor_w32_w32"] = test_w32_bxor_w32_w32;
    test_drivers["bool_eq_w32_w32"] = test_bool_eq_w32_w32;
    test_drivers["bool_ne_w32_w32"] = test_bool_ne_w32_w32;
    test_drivers["bool_lt_w32_w32"] = test_bool_lt_w32_w32;
    test_drivers["bool_ge_w32_w32"] = test_bool_ge_w32_w32;
    test_drivers["bool_ltu_w32_w32"] = test_bool_ltu_w32_w32;
    test_drivers["bool_geu_w32_w32"] = test_bool_geu_w32_w32;
    test_drivers["w32_sra_w32_w32"] = test_w32_sra_w32_w32;
    test_drivers["w32_sll_w32_w32"] = test_w32_sll_w32_w32;
    test_drivers["w32_srl_w32_w32"] = test_w32_srl_w32_w32;
    test_drivers["w32_sext_w08"] = test_w32_sext_w08;
    test_drivers["w32_zext_w08"] = test_w32_zext_w08;
    test_drivers["w32_sext_w16"] = test_w32_sext_w16;
    test_drivers["w32_zext_w16"] = test_w32_zext_w16;
    test_drivers["void_nop"] = test_void_nop;
    test_drivers["void_mul_hw_w32_w32_t2u_w32_w32"] = test_void_mul_hw_w32_w32_t2u_w32_w32;
    test_drivers["w32_divs_w32_w32"] = test_w32_divs_w32_w32;
    test_drivers["w32_rems_w32_w32"] = test_w32_rems_w32_w32;
    test_drivers["w32_divu_w32_w32"] = test_w32_divu_w32_w32;
    test_drivers["w32_remu_w32_w32"] = test_w32_remu_w32_w32;
    test_drivers["w32_mac_w32_w32_w32"] = test_w32_mac_w32_w32_w32;
    test_drivers["w32_exp_w32"] = test_w32_exp_w32;
    test_drivers["w32_prelu_w32"] = test_w32_prelu_w32;
}
int main() {
    std::set<std::string> unknown_primitives;
    TestDrivers test_drivers;
    register_drivers0(test_drivers);
    error_stream = new std::ofstream("trv32p3_cnn_c_failures.txt");
    std::ifstream in_stream("trv32p3_cnn_testcases.txt");
    assert(in_stream.good());
    std::string s;
    char buf[8192];
    while (!in_stream.eof()) {
        in_stream.getline(buf, 8192);
        if (!in_stream.gcount()) continue;
        current_line = buf;
        std::istringstream is(current_line);
        is.setf(std::ios::hex, std::ios::basefield);
        is >> s;
        if (test_drivers.find(s) != test_drivers.end()) {
            (test_drivers[s])(is);
        }
        else {
            if (unknown_primitives.insert(s).second) {
                std::cerr << "WARNING: skipping test cases for " << s << " (no C implementation)" << std::endl;
            }
        }
    }
    delete error_stream;
    return pdg_error_count;
}
