
// File generated by pdg version U-2022.12#33f3808fcb#221128
// Copyright 2014-2022 Synopsys, Inc. All rights reserved.
// pdg -P -Iisg +wisg -D__tct_patch__=0 -D__checkers__ trv32p3_cnn

#include "trv32p3_cnn_inline_primitives.h"
#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wparentheses"
#endif

namespace trv32p3_cnn_primitive {

} // namespace trv32p3_cnn_primitive
