
-- File generated by Go version U-2022.12#33f3808fcb#221128, Wed Feb 21 17:37:19 2024
-- Copyright 2014-2022 Synopsys, Inc. All rights reserved.
-- go -I../lib -F -DIS_VHDL -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -VHDL -otrv32p3_cnn_vhdl -cgo_options.cfg -Itrv32p3_cnn_vhdl/tmp_pdg -updg -updg_controller trv32p3_cnn



architecture rtl of pipe_pidTGT is
  signal pipe_val_pidTGT_r_out : t_w32;
begin

  pidTGT_r_out <= pipe_val_pidTGT_r_out;

  p_pipe_pidTGT : process(clock)
  begin
    if clock'event and clock = '1' then
      -- (_pipe_pidTGT_ID)
      -- [ctrl.n:114][ctrl.n:155][ctrl.n:194]
      pipe_val_pidTGT_r_out <= pidTGT_w_in;

    end if;
  end process p_pipe_pidTGT;
end rtl;
