
-- File generated by Go version U-2022.12#33f3808fcb#221128, Wed Feb 21 13:01:39 2024
-- Copyright 2014-2022 Synopsys, Inc. All rights reserved.
-- go -I../lib -F -DIS_VHDL -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -VHDL -otrv32p3_cnn_vhdl -cgo_options.cfg -Itrv32p3_cnn_vhdl/tmp_pdg -updg -updg_controller trv32p3_cnn



architecture rtl of mux_x_w1 is

begin

  p_mux_x_w1 : process(bin_selector_EX,
                       X_x_w1_div_main_pdg_en_in,
                       CTt20s_rp12_cstP12_EX_in,
                       aluR_in,
                       lxR_in,
                       mpyH_in,
                       mpyL_in,
                       pidTGT_r_in,
                       x_w11_in)

  begin
    x_w1_out <= (others => '0');

    -- (x_w1_copy_x_w11_X_x_w1_div_main_pdg_en)
    if X_x_w1_div_main_pdg_en_in = '1' then
      x_w1_out <= x_w11_in;
    end if;

    case bin_selector_EX is
      when "001" => -- (luiU_copy0___CTt20s_rp12_cstP12_EX)
                    -- [alu.n:191]
        x_w1_out <= resize(CTt20s_rp12_cstP12_EX_in & "000000000000", t_w32'length);
      when "010" => -- (mpyR_copy0_mpyH_EX)
                    -- [mpy.n:76]
        x_w1_out <= mpyH_in;
      when "011" => -- (mpyR_copy0_mpyL_EX)
                    -- [mpy.n:73]
        x_w1_out <= mpyL_in;
      when "100" => -- (x_w1_copy0_aluR_EX)
                    -- [alu.n:86][alu.n:144][alu.n:177][alu.n:215](regX.n:96)
        x_w1_out <= aluR_in;
      when "101" => -- (x_w1_copy0_lxR_EX)
                    -- [ldst.n:75](regX.n:96)
        x_w1_out <= lxR_in;
      when "110" => -- (x_w1_copy0_pidTGT_EX)
                    -- [ctrl.n:157][ctrl.n:196](regX.n:96)
        x_w1_out <= pidTGT_r_in;
      when others =>
        null;
    end case;

  end process p_mux_x_w1;

end rtl;
