
-- File generated by Go version U-2022.12#33f3808fcb#221128, Wed Feb 21 13:01:39 2024
-- Copyright 2014-2022 Synopsys, Inc. All rights reserved.
-- go -I../lib -F -DIS_VHDL -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -VHDL -otrv32p3_cnn_vhdl -cgo_options.cfg -Itrv32p3_cnn_vhdl/tmp_pdg -updg -updg_controller trv32p3_cnn



architecture rtl of mux_ocd_swbreak is

begin

  p_mux_ocd_swbreak : process(ohe_selector_EX)

  begin
    ocd_swbreak_out <= '0'; -- hw_init

    if ohe_selector_EX = '1' then -- (ocd_swbreak_copy0___CTt1u_cstV1_EX)
                                  -- [ocd.n:111]
      ocd_swbreak_out <= '1';
    end if;

  end process p_mux_ocd_swbreak;

end rtl;
