
-- File generated by Go version U-2022.12#33f3808fcb#221128, Wed Feb 21 17:37:19 2024
-- Copyright 2014-2022 Synopsys, Inc. All rights reserved.
-- go -I../lib -F -DIS_VHDL -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -VHDL -otrv32p3_cnn_vhdl -cgo_options.cfg -Itrv32p3_cnn_vhdl/tmp_pdg -updg -updg_controller trv32p3_cnn



architecture rtl of mux_pcaA is

begin

  p_mux_pcaA : process(ohe_selector_ID,
                       PC_ID_r_in,
                       x_r3_in)

  begin
    -- pcaA_out <= (others => '0');

    -- (pcaA_copy0_PC_ID_r_ID)
    -- [ctrl.n:109][ctrl.n:160]
    pcaA_out <= signed(resize(PC_ID_r_in, t_w32'length));

    if ohe_selector_ID = '1' then -- (pcaA_copy0_x_r3_ID)
                                  -- [ctrl.n:189](regX.n:89)
      pcaA_out <= x_r3_in;
    end if;

  end process p_mux_pcaA;

end rtl;
