
-- File generated by Go version U-2022.12#33f3808fcb#221128, Wed Feb 21 17:37:19 2024
-- Copyright 2014-2022 Synopsys, Inc. All rights reserved.
-- go -I../lib -F -DIS_VHDL -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -VHDL -otrv32p3_cnn_vhdl -cgo_options.cfg -Itrv32p3_cnn_vhdl/tmp_pdg -updg -updg_controller trv32p3_cnn



architecture rtl of mux_pcaB is

begin

  p_mux_pcaB : process(bin_selector_ID,
                       CTt12s_cstP20_ID_in,
                       CTt13s_s2_cstP31_12P7_11P25_10_5P8_4_1_ID_in,
                       of21_in)

  begin
                   -- pcaB_out <= (others => '0');

    -- (pcaB_copy0_of21_ID)
    -- [ctrl.n:161]
    pcaB_out <= resize(of21_in, t_w32'length);

    case bin_selector_ID is
      when "01" => -- (pcaB_copy0___CTt12s_cstP20_ID)
                   -- [ctrl.n:190]
        pcaB_out <= resize(CTt12s_cstP20_ID_in, t_w32'length);
      when "10" => -- (pcaB_copy0___CTt13s_s2_cstP31_12P7_11P25_10_5P8_4_1_ID)
                   -- [ctrl.n:110]
        pcaB_out <= resize(CTt13s_s2_cstP31_12P7_11P25_10_5P8_4_1_ID_in, t_w32'length);
      when others =>
        null;
    end case;

  end process p_mux_pcaB;

end rtl;
