
-- File generated by Go version U-2022.12#33f3808fcb#221128, Wed Feb 21 17:37:19 2024
-- Copyright 2014-2022 Synopsys, Inc. All rights reserved.
-- go -I../lib -F -DIS_VHDL -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -VHDL -otrv32p3_cnn_vhdl -cgo_options.cfg -Itrv32p3_cnn_vhdl/tmp_pdg -updg -updg_controller trv32p3_cnn



architecture rtl of mux_ocd_data_w is

begin

  p_mux_ocd_data_w : process(ocd_ld_DMbS3_r_in,
                             dmb_rd_dp_in)

  begin
    ocd_data_w_out <= (others => '0');

    -- (ocd_data_w_copy0_dmb_rd___ocd_ld_DMbS3_r_S3_alw)
    if ocd_ld_DMbS3_r_in then
      -- [ocd.n:73]
      ocd_data_w_out <= dmb_rd_dp_in;
    end if;

  end process p_mux_ocd_data_w;

end rtl;
