
-- File generated by Go version U-2022.12#33f3808fcb#221128, Wed Feb 21 17:37:19 2024
-- Copyright 2014-2022 Synopsys, Inc. All rights reserved.
-- go -I../lib -F -DIS_VHDL -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -VHDL -otrv32p3_cnn_vhdl -cgo_options.cfg -Itrv32p3_cnn_vhdl/tmp_pdg -updg -updg_controller trv32p3_cnn



architecture rtl of mux_pm_addr is

begin

  p_mux_pm_addr : process(ocd_ld_PMbEX_r_in,
                          ocd_st_PMbEX_r_in,
                          pm_ld_pdg_en_in,
                          ocd_addr_r_in,
                          pm_addr1_in)

  begin
    pm_addr_out <= (others => '0');

    -- (pm_addr_copy0_ocd_addr_r___ocd_ld_PMbEX_r_EX_alw, pm_addr_copy0_ocd_addr_r___ocd_st_PMbEX_r_EX_alw)
    if ocd_ld_PMbEX_r_in then
      -- [ocd.n:89]
      pm_addr_out <= ocd_addr_r_in;
    end if;
    if ocd_st_PMbEX_r_in then
      -- [ocd.n:95]
      pm_addr_out <= ocd_addr_r_in;
    end if;

    -- (pm_addr_copy_pm_addr1_pm_ld_pdg_en)
    if pm_ld_pdg_en_in = '1' then
      pm_addr_out <= pm_addr1_in;
    end if;

  end process p_mux_pm_addr;

end rtl;
