
-- File generated by Go version U-2022.12#33f3808fcb#221128, Wed Feb 21 13:01:39 2024
-- Copyright 2014-2022 Synopsys, Inc. All rights reserved.
-- go -I../lib -F -DIS_VHDL -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -VHDL -otrv32p3_cnn_vhdl -cgo_options.cfg -Itrv32p3_cnn_vhdl/tmp_pdg -updg -updg_controller trv32p3_cnn



architecture rtl of mux_pidTGT_w is

begin

  p_mux_pidTGT_w : process(ohe_selector_ID,
                           lnk_id_in,
                           pcaR_in)

  begin
    -- pidTGT_w_out <= (others => '0');

    -- (pidTGT_copy0_lnk_id_ID)
    -- [ctrl.n:155][ctrl.n:194]
    pidTGT_w_out <= lnk_id_in;

    if ohe_selector_ID = '1' then -- (pidTGT_copy0_pcaR_ID)
                                  -- [ctrl.n:114]
      pidTGT_w_out <= pcaR_in;
    end if;

  end process p_mux_pidTGT_w;

end rtl;
