
// File generated by Go version U-2022.12#33f3808fcb#221128, Sat Mar 16 14:40:42 2024
// Copyright 2014-2022 Synopsys, Inc. All rights reserved.
// go -I../lib -F -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -Verilog -otrv32p3_cnn_vlog -cgo_options.cfg -Itrv32p3_cnn_vlog/tmp_pdg -updg -updg_controller trv32p3_cnn



`timescale 1ns/1ps

// module agu2 : agu2
module agu2
  ( input                    ohe_selector_ID,
    input      signed [31:0] aguA2_in, // w32
    input      signed [31:0] aguB2_in, // w32
    output reg signed [31:0] aguR2_out // w32
  );


`include "primitives.v"

  always @ (*)

  begin : p_agu2

    aguR2_out = 32'sh0;

    if (ohe_selector_ID) // (aguR2_add_aguA2_aguB2_agu2_ID)
    begin
      // [cnn.n:120]
      w32_add_w32_w32(aguR2_out, aguA2_in, aguB2_in);
    end

  end

endmodule
