
// File generated by Go version U-2022.12#33f3808fcb#221128, Wed Apr 10 20:00:35 2024
// Copyright 2014-2022 Synopsys, Inc. All rights reserved.
// go -I../lib -F -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -Verilog -otrv32p3_cnn_vlog -cgo_options.cfg -Itrv32p3_cnn_vlog/tmp_pdg -updg -updg_controller trv32p3_cnn



`timescale 1ns/1ps

// module cnn : cnn
module cnn
  ( input              [1:0] bin_selector_EX,
    input      signed [31:0] xuA_in, // w32
    input      signed [31:0] z_r1_in, // w32
    input      signed [31:0] z_r2_in, // w32
    input      signed [31:0] z_r3_in, // w32
    input      signed [31:0] z_r4_in, // w32
    input      signed [31:0] z_r5_in, // w32
    output reg signed [31:0] cnn_R_out, // w32
    output reg signed [31:0] z_w3_out, // w32
    output reg signed [31:0] z_w4_out, // w32
    output reg signed [31:0] z_w5_out // w32
  );


`include "primitives.v"

  always @ (*)

  begin : p_cnn

    cnn_R_out = 32'sh0;
    z_w3_out = 32'sh0;
    z_w4_out = 32'sh0;
    z_w5_out = 32'sh0;

    case (bin_selector_EX)
      2'b01 : // (cnn_R_exp_xuA_cnn_EX)
      begin
        // [cnn.n:56]
        w32_exp_w32(cnn_R_out, xuA_in);
      end
      2'b10 : // (z_w3_incmac_z_r3_z_r1_z_r2_z_r4_z_w4_z_r5_z_w5_cnn_EX)
      begin
        // [cnn.n:83]
        w32_incmac_w32_w32_w32_w32_w32_w32_w32(z_w3_out, z_r3_in, z_r1_in, z_r2_in, z_r4_in, z_w4_out, z_r5_in, z_w5_out);
      end
      2'b11 : // (cnn_R_prelu_xuA_cnn_EX)
      begin
        // [cnn.n:57]
        w32_prelu_w32(cnn_R_out, xuA_in);
      end
      default :
        ; // null
    endcase

  end

endmodule
