
-- File generated by Go version U-2022.12#33f3808fcb#221128, Wed Feb 21 17:37:19 2024
-- Copyright 2014-2022 Synopsys, Inc. All rights reserved.
-- go -I../lib -F -DIS_VHDL -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -VHDL -otrv32p3_cnn_vhdl -cgo_options.cfg -Itrv32p3_cnn_vhdl/tmp_pdg -updg -updg_controller trv32p3_cnn



library ieee;
use ieee.std_logic_1164.all;

package cntrl_types is
  type t_EX_enabling is record
    -- 35 bits.
    alu_bin_sel_EX : std_logic_vector(3 downto 0);
    cmp_bin_sel_EX : std_logic_vector(2 downto 0);
    divR_divs_divA_divB_div_EX : std_logic;
    divR_divu_divA_divB_div_EX : std_logic;
    divR_rems_divA_divB_div_EX : std_logic;
    divR_remu_divA_divB_div_EX : std_logic;
    lx_bin_sel_EX : std_logic_vector(2 downto 0);
    mpy_ohe_sel_EX : std_logic;
    cnn_ohe_sel_EX : std_logic;
    controller_ohe_sel_EX : std_logic;
    reg_X_bin_sel_EX : std_logic_vector(1 downto 0);
    mem_DMb_bin_sel_EX : std_logic_vector(2 downto 0);
    mux_dmb_wr_ohe_sel_EX : std_logic;
    mux_x_w1_bin_sel_EX : std_logic_vector(2 downto 0);
    mux_x_w1_dead_ohe_sel_EX : std_logic;
    mux_aluA_ohe_sel_EX : std_logic;
    mux_aluB_bin_sel_EX : std_logic_vector(1 downto 0);
    mux_mpyM_bin_sel_EX : std_logic_vector(1 downto 0);
    mux_ocd_swbreak_ohe_sel_EX : std_logic;
    mux_X_x_w1_wad_ohe_sel_EX : std_logic;
    hazards_decode_EX : std_logic;
  end record;

  type t_ID_enabling is record
    -- 24 bits.
    pca_ohe_sel_ID : std_logic;
    agu_ohe_sel_ID : std_logic;
    controller_bin_sel_ID : std_logic_vector(1 downto 0);
    reg_PC_EX_ohe_sel_ID : std_logic;
    mem_DMb_bin_sel_ID : std_logic_vector(2 downto 0);
    mux_dm_addr_ohe_sel_ID : std_logic;
    mux_pcaA_ohe_sel_ID : std_logic;
    mux_pcaB_bin_sel_ID : std_logic_vector(1 downto 0);
    mux_jmp_tgt_ID_ohe_sel_ID : std_logic;
    mux_aguB_bin_sel_ID : std_logic_vector(1 downto 0);
    mux_pidTGT_w_ohe_sel_ID : std_logic;
    hazards_decode_ID : std_logic_vector(7 downto 0);
  end record;

  function init_EX_enabling return t_EX_enabling;
  function init_ID_enabling return t_ID_enabling;

end cntrl_types;



package body cntrl_types is

  function init_EX_enabling return t_EX_enabling is
    variable enab : t_EX_enabling;
  begin
    enab.alu_bin_sel_EX := (others => '0');
    enab.cmp_bin_sel_EX := (others => '0');
    enab.divR_divs_divA_divB_div_EX := '0';
    enab.divR_divu_divA_divB_div_EX := '0';
    enab.divR_rems_divA_divB_div_EX := '0';
    enab.divR_remu_divA_divB_div_EX := '0';
    enab.lx_bin_sel_EX := (others => '0');
    enab.mpy_ohe_sel_EX := '0';
    enab.cnn_ohe_sel_EX := '0';
    enab.controller_ohe_sel_EX := '0';
    enab.reg_X_bin_sel_EX := (others => '0');
    enab.mem_DMb_bin_sel_EX := (others => '0');
    enab.mux_dmb_wr_ohe_sel_EX := '0';
    enab.mux_x_w1_bin_sel_EX := (others => '0');
    enab.mux_x_w1_dead_ohe_sel_EX := '0';
    enab.mux_aluA_ohe_sel_EX := '0';
    enab.mux_aluB_bin_sel_EX := (others => '0');
    enab.mux_mpyM_bin_sel_EX := (others => '0');
    enab.mux_ocd_swbreak_ohe_sel_EX := '0';
    enab.mux_X_x_w1_wad_ohe_sel_EX := '0';
    enab.hazards_decode_EX := '0';
    return enab;
  end init_EX_enabling;

  function init_ID_enabling return t_ID_enabling is
    variable enab : t_ID_enabling;
  begin
    enab.pca_ohe_sel_ID := '0';
    enab.agu_ohe_sel_ID := '0';
    enab.controller_bin_sel_ID := (others => '0');
    enab.reg_PC_EX_ohe_sel_ID := '0';
    enab.mem_DMb_bin_sel_ID := (others => '0');
    enab.mux_dm_addr_ohe_sel_ID := '0';
    enab.mux_pcaA_ohe_sel_ID := '0';
    enab.mux_pcaB_bin_sel_ID := (others => '0');
    enab.mux_jmp_tgt_ID_ohe_sel_ID := '0';
    enab.mux_aguB_bin_sel_ID := (others => '0');
    enab.mux_pidTGT_w_ohe_sel_ID := '0';
    enab.hazards_decode_ID := (others => '0');
    return enab;
  end init_ID_enabling;

end cntrl_types;
