
-- File generated by Go version U-2022.12#33f3808fcb#221128, Wed Feb 21 13:01:39 2024
-- Copyright 2014-2022 Synopsys, Inc. All rights reserved.
-- go -I../lib -F -DIS_VHDL -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -VHDL -otrv32p3_cnn_vhdl -cgo_options.cfg -Itrv32p3_cnn_vhdl/tmp_pdg -updg -updg_controller trv32p3_cnn



library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library trv32p3_cnn_lib;
use trv32p3_cnn_lib.data_types.all;

-- entity debug_controller : debug_controller
entity debug_controller is
  generic (
    nid_gen : natural := 1);
  port (
    reset_ext : in std_logic;
    clock : in std_logic;
    dbg_data_pi_in : in std_logic_vector(31 downto 0);
    dbg_data_we_in : in std_logic;
    dbg_ext_break_in : in std_logic;
    dbg_instr_exec_in : in std_logic;
    jtag_ireg_in : in t_jtag_instr_tp;
    ocd_addr_pdcr_in : in t_addr;
    ocd_data_pdcr_in : in t_w08;
    ocd_instr_pdcr_in : in t_iword;
    ocd_mode_in : in t_t1u;
    ocd_swbreak_in : in t_t1u;
    pcr_in : in t_addr;
    dbg_data_po_out : out std_logic_vector(31 downto 0);
    dbg_reset_out : out std_logic;
    dbg_set_break_out : out std_logic;
    en_ocd_addr_pdcw_out : out std_logic;
    en_ocd_data_pdcw_out : out std_logic;
    en_ocd_instr_pdcw_out : out std_logic;
    ocd_addr_pdcw_out : out t_addr;
    ocd_data_pdcw_out : out t_w08;
    ocd_exe_out : out t_t1u;
    ocd_instr_pdcw_out : out t_iword;
    ocd_ld_DMb_out : out boolean;
    ocd_ld_PMb_out : out boolean;
    ocd_req_out : out t_t1u;
    ocd_st_DMb_out : out boolean;
    ocd_st_PMb_out : out boolean);
end debug_controller;
