
-- File generated by Go version U-2022.12#33f3808fcb#221128, Wed Feb 21 13:01:39 2024
-- Copyright 2014-2022 Synopsys, Inc. All rights reserved.
-- go -I../lib -F -DIS_VHDL -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -VHDL -otrv32p3_cnn_vhdl -cgo_options.cfg -Itrv32p3_cnn_vhdl/tmp_pdg -updg -updg_controller trv32p3_cnn



library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library trv32p3_cnn_lib;
use trv32p3_cnn_lib.data_types.all;

-- entity jtag_scan_register : jtag_scan_register
entity jtag_scan_register is
  generic (
    scan_reg_width_gen : natural := 16);
  port (
    jtag_trst : in std_logic;
    jtag_capture_dr_in : in std_logic;
    jtag_par_in : in std_logic_vector(scan_reg_width_gen-1 downto 0);
    jtag_shift_dr_in : in std_logic;
    jtag_si_in : in std_logic;
    jtag_tck_in : in std_logic;
    jtag_update_dr_in : in std_logic;
    jtag_par_out : out std_logic_vector(scan_reg_width_gen-1 downto 0);
    jtag_so_out : out std_logic);
end jtag_scan_register;
