
-- File generated by Go version U-2022.12#33f3808fcb#221128, Wed Feb 21 13:01:39 2024
-- Copyright 2014-2022 Synopsys, Inc. All rights reserved.
-- go -I../lib -F -DIS_VHDL -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -VHDL -otrv32p3_cnn_vhdl -cgo_options.cfg -Itrv32p3_cnn_vhdl/tmp_pdg -updg -updg_controller trv32p3_cnn



library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library trv32p3_cnn_lib;
use trv32p3_cnn_lib.data_types.all;

-- entity jtag_interface : jtag_interface
entity jtag_interface is
  port (
    jtag_trst : in std_logic;
    reset_ext : in std_logic;
    clock : in std_logic;
    dbg_data_po_in : in std_logic_vector(31 downto 0);
    jtag_capture_dr_in : in std_logic;
    jtag_shift_dr_in : in std_logic;
    jtag_si_in : in std_logic;
    jtag_tck_in : in std_logic;
    jtag_update_dr_in : in std_logic;
    jtag_update_ir_in : in std_logic;
    dbg_data_pi_out : out std_logic_vector(31 downto 0);
    dbg_data_we_out : out std_logic;
    dbg_instr_exec_out : out std_logic;
    jtag_so_out : out std_logic);
end jtag_interface;
