
// File generated by noodle version U-2022.12#33f3808fcb#221128, Fri Mar  8 12:09:14 2024
// Copyright 2014-2022 Synopsys, Inc. All rights reserved.
// noodle -Pc -Iisg +wisg -D__tct_patch__=0 -Wall +NOrlt -D__chess__ -D__programmers_view__ trv32p3_cnn

// File: compile_time_constants.cpp
// Test compile-time constants : size and alignment in default and other suitable memories

extern "C" {

const int szal___schar_DMb                        [] =  //  1,  1
    { sizeof(signed char /*chess_storage(DMb)*/      ), chess_alignof(signed char /*chess_storage(DMb)*/      ) };
const int szal___schar_DMb_stat                   [] =  //  1,  1
    { sizeof(signed char   chess_storage(DMb_stat)   ), chess_alignof(signed char   chess_storage(DMb_stat)   ) };
const int szal___uchar_DMb                        [] =  //  1,  1
    { sizeof(unsigned char /*chess_storage(DMb)*/    ), chess_alignof(unsigned char /*chess_storage(DMb)*/    ) };
const int szal___uchar_DMb_stat                   [] =  //  1,  1
    { sizeof(unsigned char   chess_storage(DMb_stat)   ), chess_alignof(unsigned char   chess_storage(DMb_stat)   ) };
const int szal___sshort_DMb                       [] =  //  2,  2
    { sizeof(short /*chess_storage(DMb)*/            ), chess_alignof(short /*chess_storage(DMb)*/            ) };
const int szal___sshort_DMb_stat                  [] =  //  2,  2
    { sizeof(short   chess_storage(DMb_stat)         ), chess_alignof(short   chess_storage(DMb_stat)         ) };
const int szal___ushort_DMb                       [] =  //  2,  2
    { sizeof(unsigned short /*chess_storage(DMb)*/   ), chess_alignof(unsigned short /*chess_storage(DMb)*/   ) };
const int szal___ushort_DMb_stat                  [] =  //  2,  2
    { sizeof(unsigned short   chess_storage(DMb_stat)   ), chess_alignof(unsigned short   chess_storage(DMb_stat)   ) };
const int szal___sint_DMb                         [] =  //  4,  4
    { sizeof(int /*chess_storage(DMb)*/              ), chess_alignof(int /*chess_storage(DMb)*/              ) };
const int szal___sint_DMb_stat                    [] =  //  4,  4
    { sizeof(int   chess_storage(DMb_stat)           ), chess_alignof(int   chess_storage(DMb_stat)           ) };
const int szal___uint_DMb                         [] =  //  4,  4
    { sizeof(unsigned /*chess_storage(DMb)*/         ), chess_alignof(unsigned /*chess_storage(DMb)*/         ) };
const int szal___uint_DMb_stat                    [] =  //  4,  4
    { sizeof(unsigned   chess_storage(DMb_stat)      ), chess_alignof(unsigned   chess_storage(DMb_stat)      ) };
const int szal___slonglong_DMb                    [] =  //  8,  4
    { sizeof(long long /*chess_storage(DMb)*/        ), chess_alignof(long long /*chess_storage(DMb)*/        ) };
const int szal___slonglong_DMb_stat               [] =  //  8,  4
    { sizeof(long long   chess_storage(DMb_stat)     ), chess_alignof(long long   chess_storage(DMb_stat)     ) };
const int szal___ulonglong_DMb                    [] =  //  8,  4
    { sizeof(unsigned long long /*chess_storage(DMb)*/ ), chess_alignof(unsigned long long /*chess_storage(DMb)*/ ) };
const int szal___ulonglong_DMb_stat               [] =  //  8,  4
    { sizeof(unsigned long long   chess_storage(DMb_stat)   ), chess_alignof(unsigned long long   chess_storage(DMb_stat)   ) };
const int szal___ffloat_DMb                       [] =  //  4,  4
    { sizeof(float /*chess_storage(DMb)*/            ), chess_alignof(float /*chess_storage(DMb)*/            ) };
const int szal___ffloat_DMb_stat                  [] =  //  4,  4
    { sizeof(float   chess_storage(DMb_stat)         ), chess_alignof(float   chess_storage(DMb_stat)         ) };
const int szal___fdouble_DMb                      [] =  //  8,  4
    { sizeof(double /*chess_storage(DMb)*/           ), chess_alignof(double /*chess_storage(DMb)*/           ) };
const int szal___fdouble_DMb_stat                 [] =  //  8,  4
    { sizeof(double   chess_storage(DMb_stat)        ), chess_alignof(double   chess_storage(DMb_stat)        ) };
const int szal___Pvoid_DMb                        [] =  //  4,  4
    { sizeof(void * /*chess_storage(DMb)*/           ), chess_alignof(void * /*chess_storage(DMb)*/           ) };
const int szal___Pvoid_DMb_stat                   [] =  //  4,  4
    { sizeof(void *   chess_storage(DMb_stat)        ), chess_alignof(void *   chess_storage(DMb_stat)        ) };

} //extern "C"  (22 functions)
