
// File generated by noodle version U-2022.12#33f3808fcb#221128, Fri Mar  8 16:45:52 2024
// Copyright 2014-2022 Synopsys, Inc. All rights reserved.
// noodle -Pc -Iisg +wisg -D__tct_patch__=0 -Wall +NOrlt -D__chess__ -D__programmers_view__ trv32p3_cnn

// File: memory_PMb.cpp
// Test memory PMb pointer arithmetic stand-alone and with load/store

//!! no load/store instructions found

// Per equivalence class of types with the same representation (same size and routing)
// only one type is tested by default, the others can be tested by defining `plus_identical'.

#ifndef N // arbitrary value, adapt at will
#define N 7
#endif

extern "C" {

//!! signed char                // does not fit

//!! unsigned char              // does not fit

//!! short                      // does not fit

//!! unsigned short             // does not fit

//!! int                        // does not fit

//!! unsigned                   // does not fit

//!! long long                  // does not fit

//!! unsigned long long         // does not fit

//!! float                      // does not fit

//!! double                     // does not fit

//!! void *                     // does not fit


} //extern "C"  (0 functions)
