
-- File generated by Go version U-2022.12#33f3808fcb#221128, Wed Feb 21 17:37:19 2024
-- Copyright 2014-2022 Synopsys, Inc. All rights reserved.
-- go -I../lib -F -DIS_VHDL -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -VHDL -otrv32p3_cnn_vhdl -cgo_options.cfg -Itrv32p3_cnn_vhdl/tmp_pdg -updg -updg_controller trv32p3_cnn



architecture rtl of alu is

begin

  p_alu : process(bin_selector_EX,
                  aluA_in,
                  aluB_in)

  begin
    aluR_out <= (others => '0');

    case bin_selector_EX is
      when "0001" => -- (aluR_add_aluA_aluB_alu_EX)
                     -- [alu.n:74][alu.n:136][alu.n:213]
        w32_add_w32_w32(aluR_out, aluA_in, aluB_in);
      when "0010" => -- (aluR_band_aluA_aluB_alu_EX)
                     -- [alu.n:80][alu.n:140]
        w32_band_w32_w32(aluR_out, aluA_in, aluB_in);
      when "0011" => -- (aluR_bor_aluA_aluB_alu_EX)
                     -- [alu.n:79][alu.n:141]
        w32_bor_w32_w32(aluR_out, aluA_in, aluB_in);
      when "0100" => -- (aluR_bxor_aluA_aluB_alu_EX)
                     -- [alu.n:78][alu.n:139]
        w32_bxor_w32_w32(aluR_out, aluA_in, aluB_in);
      when "0101" => -- (aluR_sll_aluA_aluB_alu_EX)
                     -- [alu.n:81][alu.n:172]
        w32_sll_w32_w32(aluR_out, aluA_in, aluB_in);
      when "0110" => -- (aluR_slt_aluA_aluB_alu_EX)
                     -- [alu.n:76][alu.n:137]
        w32_slt_w32_w32(aluR_out, aluA_in, aluB_in);
      when "0111" => -- (aluR_sltu_aluA_aluB_alu_EX)
                     -- [alu.n:77][alu.n:138]
        w32_sltu_w32_w32(aluR_out, aluA_in, aluB_in);
      when "1000" => -- (aluR_sra_aluA_aluB_alu_EX)
                     -- [alu.n:83][alu.n:174]
        w32_sra_w32_w32(aluR_out, aluA_in, aluB_in);
      when "1001" => -- (aluR_srl_aluA_aluB_alu_EX)
                     -- [alu.n:82][alu.n:173]
        w32_srl_w32_w32(aluR_out, aluA_in, aluB_in);
      when "1010" => -- (aluR_sub_aluA_aluB_alu_EX)
                     -- [alu.n:75]
        w32_sub_w32_w32(aluR_out, aluA_in, aluB_in);
      when others =>
        null;
    end case;

  end process p_alu;

end rtl;
