
-- File generated by Go version U-2022.12#33f3808fcb#221128, Wed Feb 21 17:37:19 2024
-- Copyright 2014-2022 Synopsys, Inc. All rights reserved.
-- go -I../lib -F -DIS_VHDL -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -VHDL -otrv32p3_cnn_vhdl -cgo_options.cfg -Itrv32p3_cnn_vhdl/tmp_pdg -updg -updg_controller trv32p3_cnn



architecture rtl of cmp is

begin

  p_cmp : process(bin_selector_EX,
                  cmpA_in,
                  cmpB_in)

  begin
    cmpF_out <= false;

    case bin_selector_EX is
      when "001" => -- (cmpF_eq_cmpA_cmpB_cmp_EX)
                    -- [ctrl.n:99]
        bool_eq_w32_w32(cmpF_out, cmpA_in, cmpB_in);
      when "010" => -- (cmpF_ge_cmpA_cmpB_cmp_EX)
                    -- [ctrl.n:103]
        bool_ge_w32_w32(cmpF_out, cmpA_in, cmpB_in);
      when "011" => -- (cmpF_geu_cmpA_cmpB_cmp_EX)
                    -- [ctrl.n:104]
        bool_geu_w32_w32(cmpF_out, cmpA_in, cmpB_in);
      when "100" => -- (cmpF_lt_cmpA_cmpB_cmp_EX)
                    -- [ctrl.n:101]
        bool_lt_w32_w32(cmpF_out, cmpA_in, cmpB_in);
      when "101" => -- (cmpF_ltu_cmpA_cmpB_cmp_EX)
                    -- [ctrl.n:102]
        bool_ltu_w32_w32(cmpF_out, cmpA_in, cmpB_in);
      when "110" => -- (cmpF_ne_cmpA_cmpB_cmp_EX)
                    -- [ctrl.n:100]
        bool_ne_w32_w32(cmpF_out, cmpA_in, cmpB_in);
      when others =>
        null;
    end case;

  end process p_cmp;

end rtl;
