
-- File generated by Go version U-2022.12#33f3808fcb#221128, Wed Feb 21 13:01:39 2024
-- Copyright 2014-2022 Synopsys, Inc. All rights reserved.
-- go -I../lib -F -DIS_VHDL -DSYNTHESIS_NO_UNGROUP -D__tct_patch__=0 -VHDL -otrv32p3_cnn_vhdl -cgo_options.cfg -Itrv32p3_cnn_vhdl/tmp_pdg -updg -updg_controller trv32p3_cnn



architecture rtl of pca is

begin

  p_pca : process(ohe_selector_ID,
                  pcaA_in,
                  pcaB_in)

  begin
    pcaR_out <= (others => '0');

    if ohe_selector_ID = '1' then -- (pcaR_add_pcaA_pcaB_pca_ID)
                                  -- [ctrl.n:112][ctrl.n:163][ctrl.n:192]
      w32_add_w32_w32(pcaR_out, pcaA_in, pcaB_in);
    end if;

  end process p_pca;

end rtl;
